name: Deployment (Staging)

on:
  push:
    branches:
      - "main"
      - "release/**"
    tags-ignore:
      - "*"

permissions:
  id-token: write
  contents: read

jobs:
  staging:
    uses: ./.github/workflows/sst.deploy.yml
    with:
      environment: Staging
      sst-stage: staging
    secrets: inherit
