name: Deploy Trigger.dev

on:
  workflow_call:
    inputs:
      environment:
        description: "GitHub environment name"
        required: true
        type: string

permissions:
  contents: read
  packages: read

jobs:
  deploy-trigger:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    environment: ${{ inputs.environment }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "pnpm"
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Deploy Trigger.dev
        working-directory: ./apps/updater
        run: pnpm trigger:deploy
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}