name: Deploy Updater

on:
  workflow_call:
    inputs:
      environment:
        description: "GitHub environment name"
        required: true
        type: string
      sst-stage:
        description: "SST deployment stage"
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  deploy-updater:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    # Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
    concurrency:
      group: updater-${{ inputs.environment }}-${{ github.ref }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: "pnpm"
          
      - name: Install dependencies
        run: pnpm install
        
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Deploy Updater
        working-directory: ./apps/updater
        run: pnpm sst deploy --stage ${{ inputs.sst-stage }}
        env:
          UPDATER_API_TOKEN: ${{ secrets.UPDATER_API_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}