name: Deployment (Dev)

on:
  push:
    branches-ignore:
      - 'main'
      - 'release/**'


permissions:
  id-token: write
  contents: read

jobs:
  dev:
    uses: ./.github/workflows/sst.deploy.yml
    with:
      environment: Development
      sst-stage: dev
    secrets: inherit
