name: SST Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      sst-stage:
        required: true
        type: string
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      DATABASE_URL:
        required: true
      UPSTASH_REDIS_REST_URL:
        required: true
      UPSTASH_REDIS_REST_TOKEN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  sst-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}

    # Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
    concurrency:
      group: merge-${{ github.ref }}

    permissions:
      id-token: write
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install dependencies
        run: |
          pnpm install
      - name: Run Drizzle Migrations
        run: |
          pnpm migrate
      - name: Deploy
        run: |
          pnpm sst deploy --stage ${{ inputs.sst-stage }}
