name: Deployment (Prod)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'

permissions:
  id-token: write
  contents: read

jobs:
  prod:
    uses: ./.github/workflows/sst.deploy.yml
    with:
      environment: Production
      sst-stage: prod
    secrets: inherit
