name: Deployment (Dev)

on:
  push:
    branches-ignore:
      - 'main'
      - 'release/**'

jobs:
  Deploy:
    uses: ./.github/workflows/sst.deploy.yml
    with:
      environment: Development
      sst-stage: dev
    secrets: inherit
