name: Deploy (Staging)

on:
  push:
    branches:
      - "main"
      - "release/**"
    tags-ignore:
      - "*"

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  test:
    uses: ./.github/workflows/test.yml
  
  run-migrations:
    uses: ./.github/workflows/run-migrations.yml
    with:
      environment: Staging
    secrets: inherit

  deploy-api:
    needs: [run-migrations, test]
    uses: ./.github/workflows/deploy-api.yml
    with:
      environment: Staging
      sst-stage: staging
    secrets: inherit
    
  deploy-updater:
    needs: [run-migrations, test]
    uses: ./.github/workflows/deploy-updater.yml
    with:
      environment: Staging
      sst-stage: staging
    secrets: inherit